export const objects = [
	"anime girls",
	"bad jokes",
	"a boom box",
	"old cheese",
	"heroin",
	"sadness",
	"depression",
	"an evil villain with a plan to destroy earth",
	"a superhero on his way to stop an evil villain",
	"Dolus",
	"fat idiots",
	"a hairy potter",
	"hentai",
	"a soft knife",
	"a sharp pillow",
	"love",
	"hate",
	"a tomato",
	"a time machine that takes 1 year to travel 1 year into the future",
	"sadness disguised as happiness",
	"debt",
	"all your imaginary friends",
	"homelessness",
	"stupid bot commands",
	"bad bots",
	"ol' musky",
	"wednesday, my dudes",
	"wednesday frog",
	"flat earthers",
	"round earthers",
	"prequel memes",
	"logan paul and jake paul",
	"selfbots",
	"very big fish",
	"ur mum",
	"the biggest fattest vape",
	"donald trump's wall",
	"smash mouth - all star",
	"death",
	"tide pods",
	"divorce papers",
	"an engagement ring",
	"yourself",
	"nothing",
	"insults",
	"compliments",
	"life advice",
	"scams",
	"nothing",
	"crappy code",
	"2 million ping",
	"myself",
	"easter eggs",
	"explosives",
	"a black hole",
	"cheap servers",
	"babies",
	"oranges",
	"eggs",
	"cream puffs",
	"plasma grenades",
	"human body parts",
	"Whitney",
	"a wedding",
	"a car",
	"a chair",
	"a rickroll",
	"money",
	"an 8ball",
	"crabs",
	"bits of the sky",
	"useless polls",
	"a television",
	"a bus",
	"expensive cheese",
	"lame memes",
	"spaghetti",
	"cats",
	"free games",
	"birds",
	"potatoes",
	"a football stadium",
	"water",
	"an alarm clock",
	"air",
	"electricity",
	"music",
	"jail time",
	"watches",
	"bookshelves",
	"the sun",
	"trains",
	"iron",
	"paper",
	"a random city",
	"cheap radios",
	"doors",
	"pie",
	"squares",
	"a duck",
	"lily from at&t",
	"couples therapy",
	"beans",
	"a discord channel",
];
